[package]
name = "httpecho"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.4", features = ["full"] }
warp = "0.3"

[[bin]]
name = "httpecho"
path = "./src/main.rs"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3